services:
  db:
    image: postgres:14-alpine
    volumes:
      - $HOME/.apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d envelope_db" ]
      interval: 10s
      timeout: 5s
      retries: 3
