services:
  postgres:
    image: postgres:14-alpine
    volumes:
      - ~/.apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    ports:
      - "5432:5432"