databaseChangeLog:
  - changeSet:
      id: 1.0.0
      author: jonichi
      changes:
        - createSequence:
            sequenceName: _user_sequence
            startValue: 1
            incrementBy: 1
        - createTable:
            tableName: _user
            columns:
              - column:
                  name: id
                  type: SERIAL
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: username
                  type: VARCHAR(120)
                  constraints:
                    nullable: false
                    unique: true
                    uniqueConstraintName: user_username_unique
              - column:
                  name: email
                  type: VARCHAR(120)
                  constraints:
                    nullable: false
                    unique: true
                    uniqueConstraintName: user_email_unique
              - column:
                  name: password
                  type: VARCHAR(120)
                  constraints:
                    nullable: false
              - column:
                  name: role
                  type: VARCHAR(50)
                  constraints:
                    nullable: false
              - column:
                  name: created_date
                  type: TIMESTAMP
                  defaultValueComputed: CURRENT_TIMESTAMP
                  constraints:
                    nullable: false
              - column:
                  name: updated_date
                  type: TIMESTAMP
                  defaultValueComputed: CURRENT_TIMESTAMP
                  constraints:
                    nullable: false
  - changeSet:
      id: 1.0.0-tag
      author: jonichi
      changes:
        - tagDatabase:
            tag: 1.0.0
